名称: Rust

在:
推送:
分支: [ "main" ]
拉取请求:
分支: [ "main" ]

环境:
CARGO_TERM_COLOR: 始终

作业:
构建:

运行于: ubuntu-latest

步骤:
    - 使用: actions/checkout@v4
    - 名称: 构建
运行: cargo 构建 --详细
    - 名称: 运行测试
运行: cargo test --verbose
